# Identificadores do Projeto no SonarCloud (preencher conforme o SonarCloud indicar)
sonar.organization=pxawtyy
sonar.projectKey=pxawtyy_primeiro-pipeline

# Informações do Projeto
sonar.projectName=primeiro-pipeline
sonar.projectVersion=1.0.0

# Código Fonte e Testes
sonar.sources=src
sonar.tests=tests

# Relatórios de Cobertura de Testes
sonar.python.coverage.reportPaths=coverage-python.xml
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Codificação
sonar.sourceEncoding=UTF-8
