name: Primeira Pipeline

on:
  push:
    branches: ["main"]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar Código do Repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Configurar ambiente Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Instalar dependências
        run: pip install pytest && npm install -g jest

      - name: Testar adição
        run: pytest tests/python/test_adicao.py && jest tests/javascript/testAdicao.test.js
  
      - name: Testar subtração
        run: pytest tests/python/test_subtracao.py && jest tests/javascript/testSubtrair.test.js
  
      - name: Testar multiplicação
        run: pytest tests/python/test_multiplicacao.py && jest tests/javascript/testMultiplicar.test.js

      - name: Testar divisão
        run: pytest tests/python/test_divisao.py && jest tests/javascript/testDividir.test.js
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar Código do Repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Configurar ambiente Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      
      - name: Instalar dependências
        run: pip install flake8
      
      - name: Rodar lint
        run: flake8 tests/python && npx eslint . --ext .js,.jsx,.ts,.tsx

  deploy:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Executar Deploy
        run: echo "Deploy realizado"