name: Primeira Pipeline

on:
  push:
    branches: ["main"]

jobs:
  config:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar Código do Repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
        
      - name: Instalar dependências
        run: pip install pytest

  test_adicao:
    needs: config
    steps:
      - name: Testar adição
        run: pytest tests/test_adicao.py
  
  test_subtracao:
    needs: config
    steps:
      - name: Testar subtração
        run: pytest tests/test_subtracao.py
  
  test_multiplicacao:
    needs: config
    steps:
      - name: Testar multiplicação
        run: pytest tests/test_multiplicacao.py

  test_divisao:
    needs: config
    steps:
      - name: Testar divisão
        run: pytest tests/test_divisao.py
  
  deploy:
    needs: test_adicao, test_subtracao, test_multiplicacao, test_divisao
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy realizado"